Traceback (most recent call last):
  File "/home/haoting/.virtualenvs/connectome_confounds/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/haoting/.virtualenvs/connectome_confounds/lib/python3.8/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/haoting/.virtualenvs/connectome_confounds/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/haoting/.virtualenvs/connectome_confounds/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/haoting/.virtualenvs/connectome_confounds/lib/python3.8/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/home/haoting/.virtualenvs/connectome_confounds/lib/python3.8/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/haoting/.virtualenvs/connectome_confounds/lib/python3.8/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import warnings
warnings.filterwarnings("ignore")
from fmriprep_denoise.visualization import figures
from myst_nb import glue


# Load metric data
dataset = "ds000228"
atlas_name = "schaefer7networks"
dimension = 400
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyboardInterrupt[0m                         Traceback (most recent call last)
[0;32m/tmp/ipykernel_48628/2654582466.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mimport[0m [0mwarnings[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0mwarnings[0m[0;34m.[0m[0mfilterwarnings[0m[0;34m([0m[0;34m"ignore"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0;32mfrom[0m [0mfmriprep_denoise[0m[0;34m.[0m[0mvisualization[0m [0;32mimport[0m [0mfigures[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0;32mfrom[0m [0mmyst_nb[0m [0;32mimport[0m [0mglue[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;34m[0m[0m

[0;32m~/projects/fmriprep-denoise-benchmark/fmriprep_denoise/visualization/figures.py[0m in [0;36m<module>[0;34m[0m
[1;32m      7[0m [0;32mfrom[0m [0mfmriprep_denoise[0m[0;34m.[0m[0mfeatures[0m [0;32mimport[0m [0mget_atlas_pairwise_distance[0m[0;34m[0m[0;34m[0m[0m
[1;32m      8[0m [0;34m[0m[0m
[0;32m----> 9[0;31m [0;32mfrom[0m [0mfmriprep_denoise[0m[0;34m.[0m[0mvisualization[0m [0;32mimport[0m [0mutils[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     10[0m [0;34m[0m[0m
[1;32m     11[0m [0;34m[0m[0m

[0;32m~/projects/fmriprep-denoise-benchmark/fmriprep_denoise/visualization/utils.py[0m in [0;36m<module>[0;34m[0m
[1;32m     38[0m     [0;32mreturn[0m [0mPath[0m[0;34m([0m[0mdata_path[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     39[0m [0;34m[0m[0m
[0;32m---> 40[0;31m [0mpath_root[0m [0;34m=[0m [0mrepo2data_path[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     41[0m [0;34m[0m[0m
[1;32m     42[0m [0;32mdef[0m [0m_get_palette[0m[0;34m([0m[0morder[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/projects/fmriprep-denoise-benchmark/fmriprep_denoise/visualization/utils.py[0m in [0;36mrepo2data_path[0;34m()[0m
[1;32m     35[0m     [0mdata_req_path[0m [0;34m=[0m [0mPath[0m[0;34m([0m[0m__file__[0m[0;34m)[0m[0;34m.[0m[0mparents[0m[0;34m[[0m[0;36m2[0m[0;34m][0m [0;34m/[0m [0;34m"binder"[0m [0;34m/[0m [0;34m"data_requirement.json"[0m[0;34m[0m[0;34m[0m[0m
[1;32m     36[0m     [0mrepo2data[0m [0;34m=[0m [0mRepo2Data[0m[0;34m([0m[0mstr[0m[0;34m([0m[0mdata_req_path[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 37[0;31m     [0mdata_path[0m [0;34m=[0m [0mrepo2data[0m[0;34m.[0m[0minstall[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     38[0m     [0;32mreturn[0m [0mPath[0m[0;34m([0m[0mdata_path[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     39[0m [0;34m[0m[0m

[0;32m~/.virtualenvs/connectome_confounds/lib/python3.8/site-packages/repo2data/repo2data.py[0m in [0;36minstall[0;34m(self)[0m
[1;32m    102[0m         [0;31m# if not, it is a single assignment[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    103[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 104[0;31m             ret += [Repo2DataChild(self._data_requirement_file,
[0m[1;32m    105[0m                                    self._use_server, self._data_requirement_path).install()]
[1;32m    106[0m [0;34m[0m[0m

[0;32m~/.virtualenvs/connectome_confounds/lib/python3.8/site-packages/repo2data/repo2data.py[0m in [0;36minstall[0;34m(self)[0m
[1;32m    333[0m                 [0mos[0m[0;34m.[0m[0mmakedirs[0m[0;34m([0m[0mself[0m[0;34m.[0m[0m_dst_path[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    334[0m             [0;31m# Downloading with the right method, depending on the src type[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 335[0;31m             [0mself[0m[0;34m.[0m[0m_scan_dl_type[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    336[0m             [0;31m# If needed, decompression of the data[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    337[0m             [0mself[0m[0;34m.[0m[0m_archive_decompress[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/.virtualenvs/connectome_confounds/lib/python3.8/site-packages/repo2data/repo2data.py[0m in [0;36m_scan_dl_type[0;34m(self)[0m
[1;32m    313[0m         [0;31m# or from zenodo ?[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    314[0m         [0;32melif[0m [0mre[0m[0;34m.[0m[0mmatch[0m[0;34m([0m[0;34m".*?(10\.\d{4}/zenodo).*?"[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0m_data_requirement_file[0m[0;34m[[0m[0;34m"src"[0m[0;34m][0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 315[0;31m             [0mself[0m[0;34m.[0m[0m_zenodo_download[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    316[0m         [0;31m# or osf[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    317[0m         [0;32melif[0m [0mre[0m[0;34m.[0m[0mmatch[0m[0;34m([0m[0;34m".*?(https://osf.io).*?"[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0m_data_requirement_file[0m[0;34m[[0m[0;34m"src"[0m[0;34m][0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/.virtualenvs/connectome_confounds/lib/python3.8/site-packages/repo2data/repo2data.py[0m in [0;36m_zenodo_download[0;34m(self)[0m
[1;32m    252[0m               (self._data_requirement_file["src"]))
[1;32m    253[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 254[0;31m             subprocess.check_call(
[0m[1;32m    255[0m                 ['zenodo_get', '-o', self._dst_path, self._data_requirement_file["src"]])
[1;32m    256[0m         [0;32mexcept[0m [0mFileNotFoundError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/lib/python3.8/subprocess.py[0m in [0;36mcheck_call[0;34m(*popenargs, **kwargs)[0m
[1;32m    357[0m     [0mcheck_call[0m[0;34m([0m[0;34m[[0m[0;34m"ls"[0m[0;34m,[0m [0;34m"-l"[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    358[0m     """
[0;32m--> 359[0;31m     [0mretcode[0m [0;34m=[0m [0mcall[0m[0;34m([0m[0;34m*[0m[0mpopenargs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    360[0m     [0;32mif[0m [0mretcode[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    361[0m         [0mcmd[0m [0;34m=[0m [0mkwargs[0m[0;34m.[0m[0mget[0m[0;34m([0m[0;34m"args"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/lib/python3.8/subprocess.py[0m in [0;36mcall[0;34m(timeout, *popenargs, **kwargs)[0m
[1;32m    340[0m     [0;32mwith[0m [0mPopen[0m[0;34m([0m[0;34m*[0m[0mpopenargs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m [0;32mas[0m [0mp[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    341[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 342[0;31m             [0;32mreturn[0m [0mp[0m[0;34m.[0m[0mwait[0m[0;34m([0m[0mtimeout[0m[0;34m=[0m[0mtimeout[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    343[0m         [0;32mexcept[0m[0;34m:[0m  [0;31m# Including KeyboardInterrupt, wait handled that.[0m[0;34m[0m[0;34m[0m[0m
[1;32m    344[0m             [0mp[0m[0;34m.[0m[0mkill[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/lib/python3.8/subprocess.py[0m in [0;36mwait[0;34m(self, timeout)[0m
[1;32m   1081[0m             [0mendtime[0m [0;34m=[0m [0m_time[0m[0;34m([0m[0;34m)[0m [0;34m+[0m [0mtimeout[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1082[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1083[0;31m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_wait[0m[0;34m([0m[0mtimeout[0m[0;34m=[0m[0mtimeout[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1084[0m         [0;32mexcept[0m [0mKeyboardInterrupt[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1085[0m             [0;31m# https://bugs.python.org/issue25942[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/lib/python3.8/subprocess.py[0m in [0;36m_wait[0;34m(self, timeout)[0m
[1;32m   1804[0m                         [0;32mif[0m [0mself[0m[0;34m.[0m[0mreturncode[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1805[0m                             [0;32mbreak[0m  [0;31m# Another thread waited.[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1806[0;31m                         [0;34m([0m[0mpid[0m[0;34m,[0m [0msts[0m[0;34m)[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_try_wait[0m[0;34m([0m[0;36m0[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1807[0m                         [0;31m# Check the pid and loop as waitpid has been known to[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1808[0m                         [0;31m# return 0 even without WNOHANG in odd situations.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/lib/python3.8/subprocess.py[0m in [0;36m_try_wait[0;34m(self, wait_flags)[0m
[1;32m   1762[0m             [0;34m"""All callers to this function MUST hold self._waitpid_lock."""[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1763[0m             [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1764[0;31m                 [0;34m([0m[0mpid[0m[0;34m,[0m [0msts[0m[0;34m)[0m [0;34m=[0m [0mos[0m[0;34m.[0m[0mwaitpid[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mpid[0m[0;34m,[0m [0mwait_flags[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1765[0m             [0;32mexcept[0m [0mChildProcessError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1766[0m                 [0;31m# This happens if SIGCLD is set to be ignored or waiting[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;31mKeyboardInterrupt[0m: 
KeyboardInterrupt: 

